### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [mbiesiad/COVID-19-World-Data#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/3CKDM4
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by mbiesiad** [comment]
Hi,
Thank you for your message. Sure, OK. I appreciate that! ⭐ 

Keep in touch.

Best wishes,

**Comment by mbiesiad** [comment]
@reeshmabijosh The update directly via Dataverse, right?

**Comment by reeshmabijosh** [comment]
Hello Michal,

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
you will get the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.
This is an example of a dataset with good metadata
https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/TZMOTL


Thanks
Reeshma K

**Comment by mbiesiad** [comment]
My pleasure! I'll take care of it ASAP (probably by the end of this week). Thank you for your help & answer.

Best wishes,
