### ISSUE TITLE
Extract Information from the Data

### ISSUE THREAD

**Issue by vamseesonti** [mbiesiad/COVID-19-World-Data#33]
Hi @mbiesiad, you can valuable insights, and visualization from the data that you have here. We can use powerful tools and languages like R or Python to achieve that. 
Let's start a discussion on how to go ahead with it and start working?

**Comment by biesiadamich** [comment]
Hello @vamseesonti Thank you for your feedback & message. Sure, great idea. R & Py are powerful 🚀

**Comment by mbiesiad** [comment]
Hello @vamseesonti Thank you for your feedback & message. Sure, great idea. R & Py are powerful 🚀

**Comment by vamseesonti** [comment]
@mbiesiad So shall we discuss the solution(s) and how to take it ahead? Maybe have a discussion this Friday/Weekend?

**Comment by mbiesiad** [comment]
Yeah, sure. What communication channel you propose? Best wishes,
