### ISSUE TITLE
Goal??

### ISSUE THREAD

**Issue by Ritu1611** [mbiesiad/COVID-19-World-Data#38]
What is our goal to achieve. Plotting and analyzing increase of cases or getting recent data

**Comment by mbiesiad** [comment]
Hi @Ritu1611 Good question, some time has passed. 

"(...) When the project was kicked off, there was a lack of the APIs or data. That was quite useful I hope (saw the stats, thank you!)."

Times have changed a little now. Yup, plotting & analyzing data will be great feature here!

**Comment by Ritu1611** [comment]
Can we use latest data from data.world or and other sources. You can suggest data source as well.

**Comment by Ritu1611** [comment]
@mbiesiad

**Comment by mbiesiad** [comment]
@Ritu1611 Thanks for your messages. I think, that the [data.world](https://data.world/) is OK. Yeah, sure. 🚀 

At this moment, stats for Poland are updated quite well. It could be nice to make an update for other files.

**Comment by rohansp** [comment]
@Ritu1611 @mbiesiad I have solid programming experience in C#.NET and VB.NET but none in Python. Can I be of any help in this project? Would like to contribute.I am good at writing SQL queries in relational databases like SQL Server, Oracle. I have basic understanding of ML.
